[project]
name = 'on-chain-subscription-service'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.access-permissions]
path = 'contracts/access-permissions.clar'
clarity_version = 3
epoch = 'latest'

[contracts.subscription-contract]
path = 'contracts/subscription-contract.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
